// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_rmw(void);
__attribute__((used))
void __component_type_object_force_link_rmw_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_rmw();
}
#endif
#include "rmw_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[resource-drop]client")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5Bresource_dropX5Dclient(int32_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[static]client.connect")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BstaticX5DclientX2Econnect(uint8_t *, size_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]client.disconnect")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DclientX2Edisconnect(int32_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[resource-drop]message")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5Bresource_dropX5Dmessage(int32_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[constructor]message")))
int32_t __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BconstructorX5Dmessage(uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.topic")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Etopic(int32_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.content-type")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Econtent_type(int32_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.set-content-type")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_content_type(int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.data")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Edata(int32_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.set-data")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_data(int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.metadata")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Emetadata(int32_t, uint8_t *);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.add-metadata")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eadd_metadata(int32_t, uint8_t *, size_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.set-metadata")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_metadata(int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/types@0.2.0-draft")))
__attribute__((import_name("[method]message.remove-metadata")))
void __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eremove_metadata(int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("wasi:messaging/producer@0.2.0-draft")))
__attribute__((import_name("send")))
void __wasm_import_wasiX3AmessagingX2FproducerX400X2E2X2E0_draftX00send(int32_t, uint8_t *, size_t, int32_t, uint8_t *);
wasi::messaging::types::Client::~Client()
{
  if (handle>=0) {
    __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5Bresource_dropX5Dclient(handle);
  }
}
std::expected<wasi::messaging::types::Client, wasi::messaging::types::Error> wasi::messaging::types::Client::Connect(std::string_view name)
{
  uintptr_t ret_area[((4*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  auto&& vec0 = name;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BstaticX5DclientX2Econnect(std::move(ptr0), std::move(len0), std::move(ptr1));
  std::optional<std::expected<types::Client, types::Error>> result7_opt;
  if ((int32_t) (*((uint8_t*) (ptr1 + 0)))==0) {
    int32_t l2 = *((int32_t const*)(ptr1 + sizeof(void*)));

    result7_opt.emplace(std::expected<types::Client, types::Error>(wit::ResourceImportBase{l2}));
  } else {
    std::optional<types::Error> variant6_opt;
    switch ((int32_t) (*((uint8_t*) (ptr1 + sizeof(void*))))) {
      case 0: { 
        variant6_opt = types::Error{{types::Error::Timeout{}}};
      } break;
      case 1: { auto len3 = *((size_t*) (ptr1 + (3*sizeof(void*))));


      variant6_opt = types::Error{{types::Error::Connection{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len3)}}};
    } break;
    case 2: { auto len4 = *((size_t*) (ptr1 + (3*sizeof(void*))));


    variant6_opt = types::Error{{types::Error::PermissionDenied{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len4)}}};
  } break;
  case 3: { auto len5 = *((size_t*) (ptr1 + (3*sizeof(void*))));


  variant6_opt = types::Error{{types::Error::Other{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len5)}}};
} break;
}
types::Error variant6 = std::move(*variant6_opt);

result7_opt.emplace(std::unexpected{std::move(variant6)});
}
std::expected<types::Client, types::Error> result7 = std::move(*result7_opt);
auto result8 = std::move(result7);
return result8;
}
std::expected<void, wasi::messaging::types::Error> wasi::messaging::types::Client::Disconnect() const
{
  uintptr_t ret_area[((4*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  uint8_t* ptr0 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DclientX2Edisconnect((*this).get_handle(), std::move(ptr0));
  std::optional<std::expected<void, types::Error>> result5_opt;
  if ((int32_t) (*((uint8_t*) (ptr0 + 0)))==0) {
    
    result5_opt.emplace(std::expected<void, types::Error>());
  } else {
    std::optional<types::Error> variant4_opt;
    switch ((int32_t) (*((uint8_t*) (ptr0 + sizeof(void*))))) {
      case 0: { 
        variant4_opt = types::Error{{types::Error::Timeout{}}};
      } break;
      case 1: { auto len1 = *((size_t*) (ptr0 + (3*sizeof(void*))));


      variant4_opt = types::Error{{types::Error::Connection{wit::string((char const*)(*((uint8_t**) (ptr0 + (2*sizeof(void*))))), len1)}}};
    } break;
    case 2: { auto len2 = *((size_t*) (ptr0 + (3*sizeof(void*))));


    variant4_opt = types::Error{{types::Error::PermissionDenied{wit::string((char const*)(*((uint8_t**) (ptr0 + (2*sizeof(void*))))), len2)}}};
  } break;
  case 3: { auto len3 = *((size_t*) (ptr0 + (3*sizeof(void*))));


  variant4_opt = types::Error{{types::Error::Other{wit::string((char const*)(*((uint8_t**) (ptr0 + (2*sizeof(void*))))), len3)}}};
} break;
}
types::Error variant4 = std::move(*variant4_opt);

result5_opt.emplace(std::unexpected{std::move(variant4)});
}
std::expected<void, types::Error> result5 = std::move(*result5_opt);
auto result6 = std::move(result5);
return result6;
}
wasi::messaging::types::Client::Client(wit::ResourceImportBase&&b) : wit::ResourceImportBase(std::move(b)) {}
wasi::messaging::types::Message::~Message()
{
  if (handle>=0) {
    __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5Bresource_dropX5Dmessage(handle);
  }
}
wasi::messaging::types::Message::Message(std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto ret = __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BconstructorX5Dmessage(std::move(ptr0), std::move(len0));
  this->handle = wit::ResourceImportBase{ret}.into_handle();
}
std::optional<wit::string> wasi::messaging::types::Message::Topic() const
{
  uintptr_t ret_area[((3*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  uint8_t* ptr0 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Etopic((*this).get_handle(), std::move(ptr0));
  std::optional<wit::string> option2;
  if ((int32_t) (*((uint8_t*) (ptr0 + 0)))) {
    auto len1 = *((size_t*) (ptr0 + (2*sizeof(void*))));


    option2.emplace(wit::string((char const*)(*((uint8_t**) (ptr0 + sizeof(void*)))), len1));
  }
  auto result3 = std::move(option2);
  return result3;
}
std::optional<wit::string> wasi::messaging::types::Message::ContentType() const
{
  uintptr_t ret_area[((3*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  uint8_t* ptr0 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Econtent_type((*this).get_handle(), std::move(ptr0));
  std::optional<wit::string> option2;
  if ((int32_t) (*((uint8_t*) (ptr0 + 0)))) {
    auto len1 = *((size_t*) (ptr0 + (2*sizeof(void*))));


    option2.emplace(wit::string((char const*)(*((uint8_t**) (ptr0 + sizeof(void*)))), len1));
  }
  auto result3 = std::move(option2);
  return result3;
}
void wasi::messaging::types::Message::SetContentType(std::string_view content_type) const
{
  auto&& vec0 = content_type;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_content_type((*this).get_handle(), std::move(ptr0), std::move(len0));
}
wit::vector<uint8_t> wasi::messaging::types::Message::Data() const
{
  uintptr_t ret_area[((2*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  uint8_t* ptr0 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Edata((*this).get_handle(), std::move(ptr0));
  auto len1 = *((size_t*) (ptr0 + sizeof(void*)));
  auto result2 = wit::vector<uint8_t>((uint8_t*)(*((uint8_t**) (ptr0 + 0))), len1);
  return result2;
}
void wasi::messaging::types::Message::SetData(std::span<uint8_t const> data) const
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_data((*this).get_handle(), std::move(ptr0), std::move(len0));
}
std::optional<wit::vector<std::tuple<wit::string, wit::string>>> wasi::messaging::types::Message::Metadata() const
{
  uintptr_t ret_area[((3*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  uint8_t* ptr0 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Emetadata((*this).get_handle(), std::move(ptr0));
  std::optional<wit::vector<std::tuple<wit::string, wit::string>>> option5;
  if ((int32_t) (*((uint8_t*) (ptr0 + 0)))) {
    auto base4 = *((uint8_t**) (ptr0 + sizeof(void*)));
    auto len4 = *((size_t*) (ptr0 + (2*sizeof(void*))));
    auto result4 = wit::vector<std::tuple<wit::string, wit::string>>::allocate(len4);
    for (unsigned i=0; i<len4; ++i) {
      auto base = base4 + i * (4*sizeof(void*));
      auto len1 = *((size_t*) (base + sizeof(void*)));

      auto len2 = *((size_t*) (base + (3*sizeof(void*))));

      auto tuple3 = std::tuple<wit::string, wit::string>(wit::string((char const*)(*((uint8_t**) (base + 0))), len1), wit::string((char const*)(*((uint8_t**) (base + (2*sizeof(void*))))), len2));
      auto e4 = std::move(tuple3);
      result4.initialize(i, std::move(e4));
    }

    option5.emplace(std::move(result4));
  }
  auto result6 = std::move(option5);
  return result6;
}
void wasi::messaging::types::Message::AddMetadata(std::string_view key, std::string_view value) const
{
  auto&& vec0 = key;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto&& vec1 = value;
  auto ptr1 = (uint8_t*)(vec1.data());
  auto len1 = (size_t)(vec1.size());
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eadd_metadata((*this).get_handle(), std::move(ptr0), std::move(len0), std::move(ptr1), std::move(len1));
}
void wasi::messaging::types::Message::SetMetadata(std::span<std::tuple<std::string_view, std::string_view> const> meta) const
{
  auto&& vec2 = meta;
  auto ptr2 = (uint8_t*)(vec2.data());
  auto len2 = (size_t)(vec2.size());
  for (size_t i = 0; i < len2; ++i) {
    auto base = ptr2 + i * (4*sizeof(void*));
    auto&& IterElem = vec2[i];
    auto&& vec0 = std::get<0>(IterElem);
    auto ptr0 = (uint8_t*)(vec0.data());
    auto len0 = (size_t)(vec0.size());
    *((size_t*)(base + sizeof(void*))) = len0;
    *((uint8_t**)(base + 0)) = ptr0;
    auto&& vec1 = std::get<1>(IterElem);
    auto ptr1 = (uint8_t*)(vec1.data());
    auto len1 = (size_t)(vec1.size());
    *((size_t*)(base + (3*sizeof(void*)))) = len1;
    *((uint8_t**)(base + (2*sizeof(void*)))) = ptr1;

  }
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eset_metadata((*this).get_handle(), std::move(ptr2), std::move(len2));
}
void wasi::messaging::types::Message::RemoveMetadata(std::string_view key) const
{
  auto&& vec0 = key;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_wasiX3AmessagingX2FtypesX400X2E2X2E0_draftX00X5BmethodX5DmessageX2Eremove_metadata((*this).get_handle(), std::move(ptr0), std::move(len0));
}
wasi::messaging::types::Message::Message(wit::ResourceImportBase&&b) : wit::ResourceImportBase(std::move(b)) {}
std::expected<void, wasi::messaging::types::Error> wasi::messaging::producer::Send(std::reference_wrapper<const types::Client> c, std::string_view topic, types::Message&& message)
{
  uintptr_t ret_area[((4*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  auto&& vec0 = topic;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  __wasm_import_wasiX3AmessagingX2FproducerX400X2E2X2E0_draftX00send(c.get().get_handle(), std::move(ptr0), std::move(len0), message.into_handle(), std::move(ptr1));
  std::optional<std::expected<void, types::Error>> result6_opt;
  if ((int32_t) (*((uint8_t*) (ptr1 + 0)))==0) {
    
    result6_opt.emplace(std::expected<void, types::Error>());
  } else {
    std::optional<types::Error> variant5_opt;
    switch ((int32_t) (*((uint8_t*) (ptr1 + sizeof(void*))))) {
      case 0: { 
        variant5_opt = types::Error{{types::Error::Timeout{}}};
      } break;
      case 1: { auto len2 = *((size_t*) (ptr1 + (3*sizeof(void*))));


      variant5_opt = types::Error{{types::Error::Connection{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len2)}}};
    } break;
    case 2: { auto len3 = *((size_t*) (ptr1 + (3*sizeof(void*))));


    variant5_opt = types::Error{{types::Error::PermissionDenied{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len3)}}};
  } break;
  case 3: { auto len4 = *((size_t*) (ptr1 + (3*sizeof(void*))));


  variant5_opt = types::Error{{types::Error::Other{wit::string((char const*)(*((uint8_t**) (ptr1 + (2*sizeof(void*))))), len4)}}};
} break;
}
types::Error variant5 = std::move(*variant5_opt);

result6_opt.emplace(std::unexpected{std::move(variant5)});
}
std::expected<void, types::Error> result6 = std::move(*result6_opt);
auto result7 = std::move(result6);
return result7;
}
extern "C" __attribute__((__export_name__("wasi:messaging/incoming-handler@0.2.0-draft#handle")))
uint8_t * __wasm_export_wasiX3AmessagingX2Fincoming_handlerX400X2E2X2E0_draftX23handle(int32_t arg0)
{
  static uintptr_t ret_area[((4*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  auto obj0 = wasi::messaging::types::Message(wit::ResourceImportBase{arg0});
  auto result1 = exports::wasi::messaging::incoming_handler::Handle(std::move(obj0));
  uint8_t* ptr2 = (uint8_t*)(&ret_area);
  if ((result1).has_value()) {
    
    *((int8_t*)(ptr2 + 0)) = (int32_t(0));
  } else {
    wasi::messaging::types::Error payload4 = std::move(result1).error();
    *((int8_t*)(ptr2 + 0)) = (int32_t(1));
    switch ((int32_t) (payload4).variants.index()) {
      case 0: {
        *((int8_t*)(ptr2 + sizeof(void*))) = (int32_t(0));
        break;
      }
      case 1: {
        auto& payload6 = std::get<wasi::messaging::types::Error::Connection>(payload4.variants).value;
        *((int8_t*)(ptr2 + sizeof(void*))) = (int32_t(1));
        auto&& vec7 = payload6;
        auto ptr7 = (uint8_t*)(vec7.data());
        auto len7 = (size_t)(vec7.size());
        payload6.leak();

        *((size_t*)(ptr2 + (3*sizeof(void*)))) = len7;
        *((uint8_t**)(ptr2 + (2*sizeof(void*)))) = ptr7;
        break;
      }
      case 2: {
        auto& payload8 = std::get<wasi::messaging::types::Error::PermissionDenied>(payload4.variants).value;
        *((int8_t*)(ptr2 + sizeof(void*))) = (int32_t(2));
        auto&& vec9 = payload8;
        auto ptr9 = (uint8_t*)(vec9.data());
        auto len9 = (size_t)(vec9.size());
        payload8.leak();

        *((size_t*)(ptr2 + (3*sizeof(void*)))) = len9;
        *((uint8_t**)(ptr2 + (2*sizeof(void*)))) = ptr9;
        break;
      }
      case 3: {
        auto& payload10 = std::get<wasi::messaging::types::Error::Other>(payload4.variants).value;
        *((int8_t*)(ptr2 + sizeof(void*))) = (int32_t(3));
        auto&& vec11 = payload10;
        auto ptr11 = (uint8_t*)(vec11.data());
        auto len11 = (size_t)(vec11.size());
        payload10.leak();

        *((size_t*)(ptr2 + (3*sizeof(void*)))) = len11;
        *((uint8_t**)(ptr2 + (2*sizeof(void*)))) = ptr11;
        break;
      }
    }
  }
  return ptr2;
}
extern "C" __attribute__((__weak__, __export_name__("cabi_post_wasi:messaging/incoming-handler@0.2.0-draft#handle")))
void cabi_post_wasiX3AmessagingX2Fincoming_handlerX400X2E2X2E0_draftX23handle(uint8_t * arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + sizeof(void*))))) {
        case 0: {
          break;
        }
        case 1: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + (2*sizeof(void*))))));
          }
          break;
        }
        case 2: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + (2*sizeof(void*))))));
          }
          break;
        }
        case 3: {
          if ((*((size_t*) (arg0 + (3*sizeof(void*))))) > 0) {
            wit::string::drop_raw((void*) (*((uint8_t**) (arg0 + (2*sizeof(void*))))));
          }
          break;
        }
      }
      break;
    }
  }
}

// Component Adapters
