// Generated by `wit-bindgen` 0.48.1. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_RMW_H
#define __CPP_GUEST_BINDINGS_RMW_H
#include <cstdint>
#include <utility>
#include <string_view>
#include <expected>
#include <optional>
#include <cassert>
#include <variant>
#include <tuple>
#include "wit.h"
namespace wasi {
  namespace messaging {
    namespace types {
      class Client;
      class Message;
      /// A type alias for string to represent a message topic
      using Topic = wit::string;
      /// Errors that can occur when using the messaging interface.
      struct Error {
        /// The request or operation timed out.
        struct Timeout {};
        /// An error occurred with the connection. Includes a message for additional context
        struct Connection { wit::string value; };
        /// A permission error occurred. Includes a message for additional context
        struct PermissionDenied { wit::string value; };
        /// A catch all for other types of errors
        struct Other { wit::string value; };
        std::variant<Timeout, Connection, PermissionDenied, Other> variants;
      };
      class Client : public wit::ResourceImportBase{

        public:

        ~Client();
        static std::expected<Client, Error> Connect(std::string_view name);
        std::expected<void, Error> Disconnect() const;
        Client(wit::ResourceImportBase &&);
        Client(Client&&) = default;
        Client& operator=(Client&&) = default;
      };

      class Message : public wit::ResourceImportBase{

        public:

        ~Message();
        Message(std::span<uint8_t const> data);
        std::optional<wit::string> Topic() const;
        std::optional<wit::string> ContentType() const;
        void SetContentType(std::string_view content_type) const;
        wit::vector<uint8_t> Data() const;
        void SetData(std::span<uint8_t const> data) const;
        std::optional<wit::vector<std::tuple<wit::string, wit::string>>> Metadata() const;
        void AddMetadata(std::string_view key, std::string_view value) const;
        void SetMetadata(std::span<std::tuple<std::string_view, std::string_view> const> meta) const;
        void RemoveMetadata(std::string_view key) const;
        Message(wit::ResourceImportBase &&);
        Message(Message&&) = default;
        Message& operator=(Message&&) = default;
      };

    }
    namespace producer {
      using Client = types::Client;
      using Message = types::Message;
      using Error = types::Error;
      using Topic = wit::string;
      std::expected<void, types::Error> Send(std::reference_wrapper<const types::Client> c, std::string_view topic, types::Message&& message);
      // export_interface Interface(Id { idx: 1 })
    }
  }
}
namespace exports {
  namespace wasi {
    namespace messaging {
      namespace incoming_handler {
        using Message = ::wasi::messaging::types::Message;
        using Error = ::wasi::messaging::types::Error;
        using Topic = wit::string;
        std::expected<void, ::wasi::messaging::types::Error> Handle(::wasi::messaging::types::Message&& message);
      }
    }
  }
}

#endif
